EnterpriseAppMvc/EnterpriseAppMvc/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EnterpriseAppMvc.Domain.Entities;

//  Michael Webster
//  Assignment 3 - Enterprise App with MVC
//  PROG30000 - Enterprise Software Systems
//  November 27th 2016 11:59 PM

namespace EnterpriseAppMvc.Controllers
{
    /// <summary>
    /// The InvoiceController will handle all of the logic relating to invoices and the views that associate with them
    /// </summary>
    public class InvoiceController : Controller
    {
        /// <summary>
        /// The USER_TYPE_NAME is a constant string which will serve as the name of the session object to hold the information
        /// about which type of user is currently signed in (admin or normal)
        /// </summary>
        private const string USER_ACCOUNT = "UserAccount";

        /// <summary>
        /// The USER_NAME const variable will serve as the name of the session object to hold the string of the username of the user using
        /// the web app
        /// </summary>
        private const string USER_NAME = "UserName";

        /// <summary>
        /// This constant variable will be the string of the name of the session which will keep track of the invoice list 
        /// </summary>
        private const string INVOICE_REGISTER_SESSION_NAME = "Invoices";

        
        private IRegisteredInvoices _registeredInvoices;

        /// <summary>
        /// The constructor will initialize the registered invoices class to allow access to its methods
        /// </summary>
        public InvoiceController(IRegisteredInvoices regInv)
        {

            _registeredInvoices = regInv;
        }
        /// <summary>
        /// The InvoiceRegister class will hold the information relating the the invoices registered in the web application. It will
        /// store it in a session variable so it may be used throughout the entirety of the state of the web application
        /// </summary>
        public IRegisteredInvoices InvoiceRegister
        {
            get
            {    
                if (Session[INVOICE_REGISTER_SESSION_NAME] == null) //if the session does not exist, make it equal the newly created RegisteredInvoice object
                {
                    Session[INVOICE_REGISTER_SESSION_NAME] = _registeredInvoices;
                }
                else //the session exists, so it may reused
                {
                    _registeredInvoices = Session[INVOICE_REGISTER_SESSION_NAME] as IRegisteredInvoices;
                }
                return _registeredInvoices;
            }
        }


        /// <summary>
        /// The home ActionResult method will return the home page found in the Invoice section of the web application. From there,
        /// The user can which action they want to perform (such as viewing invoices, editing them, etc)
        /// </summary>
        /// <returns></returns>
        /// 
        public ActionResult Home()
        {
            return View();
        }

        /// <summary>
        /// The AddInvoice ActionResult method will return a view which will allow the user to create a new invoice
        /// to be added to the list of saved invoices
        /// </summary>
        /// <returns></returns>
        public ActionResult InvoiceEntry()
        {
            ViewBag.title = "Add Invoice";
            ViewBag.submitBtn = "Submit Invoice";
            return View();
        }

        /// <summary>
        /// The AddInvoice ActionResult HttpPost method will receieve the information the user entered on the form and make
        /// a new invoice. It will also verify that all of the information is entered and correct (i.e. unit price is only a decimial,
        /// quantity is an int, etc). If the invoice is being editted, it will be updated.
        /// </summary>
        /// <param name="invoice"></param>
        /// <param name="shipDate"></param>
        /// <param name="payDate"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult InvoiceEntry(Invoice invoice)
        {
            
            //check to see if all the information has been added properly
            if (ModelState.IsValid)
            {
                InvoiceRegister.AddInvoice(invoice);
                ViewBag.message = "The invoice was added successfully!";
                return View("Home");
            }
            //the information was not entered correctly. Return the view to the user
            else
            {
                ViewBag.submitBtn = "Add Invoice";
                if (invoice.InvoiceNumber != 0) //if the invoice already existed, make the reviewing state of the page true again
                {
                    ViewBag.isReviewing = true;
                    ViewBag.submitBtn = "Edit Invoice";
                }
                return View(InvoiceRegister.InvoiceList.FirstOrDefault(inv => inv.InvoiceNumber == invoice.InvoiceNumber));//make sure the invoice being editted before is being returned
            }
        }


        /// <summary>
        /// The ViewInvoices ActionResult method will return view that will display a list of the current invoices available
        /// to the admin viewing it
        /// </summary>
        /// <returns></returns>
        public ActionResult ViewInvoices(string message)
        {

            ViewBag.message = message;
            return View(_registeredInvoices.FindInvoice(inv => inv.Paid == false));
        }

        /// <summary>
        /// The manageInvoice ActionResult method will return the same view that was used to display the ability to 
        /// add invoices
        /// </summary>
        /// <returns></returns>
        public ActionResult ManageInvoice(string trackingNum)
        {
            int trackingNumber = int.Parse(trackingNum);
            Invoice invoice = InvoiceRegister.InvoiceList.FirstOrDefault(i => i.InvoiceNumber == trackingNumber);
            
            //set viewbag values to allow the page to display as an editable invoice
            ViewBag.isReviewing = true;
            ViewBag.title = "Edit Invoice";
            ViewBag.submitBtn = "Edit Invoice";
            return View("InvoiceEntry", invoice);
        }
        /// <summary>
        /// method which will log the user out and end the session
        /// </summary>
        /// <returns></returns>
        public ActionResult Logout()
        {
            Session.RemoveAll();
            return RedirectToAction("Index", "UserAccount");

        }
    }
}

EnterpriseAppMvc/EnterpriseAppMvc/Views/Invoice/Home.cshtml
@using EnterpriseAppMvc.Domain.Entities

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Home</title>
    <link rel="stylesheet" type="text/css" href="~/Content/Style.css" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
</head>
<body>
        <div class="container">
            <div class="page-header text-center">
                <h1>Invoice Home</h1>
            </div>
        </div>
        @if (Session["UserAccount"] != null)
        {
            User user = Session["UserAccount"] as User;
            <div class="text-center">

                <h3 style="color:green">@ViewBag.message</h3>

                <label>Welcome, @user.Username</label><br /><br />
                <div> @Html.ActionLink("Add New Invoice", "InvoiceEntry", null, new { @class = "btn btn-success" } ) </div><br />

                @if (user.Type >= UserType.Manager)
                {
                    <div> @Html.ActionLink("View Outstanding Invoices", "ViewInvoices", null, new { @class = "btn btn-success" }) </div><br />
                }
                <div> @Html.ActionLink("Logout", "Logout", null, new { @class = "btn btn-primary" }) </div>



            </div>
        }
        else
        {
            <h3 class="text-center" style="color: red;">ERROR 403: You are currently not authenticated. Please <a href="../UserAccount/Index">return</a> to the login screen</h3>
        }
</body>
</html>

EnterpriseAppMvc/EnterpriseAppMvc/Views/Invoice/InvoiceEntry.cshtml
@using EnterpriseAppMvc.Domain.Entities;
@model Invoice

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Invoice Entry</title>
    <link rel="stylesheet" type="text/css" href="~/Content/Style.css" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
</head>
<body>

@if (Session["UserAccount"] != null)
{
    <div class="container">
        <div class="page-header text-center">
            <h1>@ViewBag.title</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <div class="well well-sm">
                <div class="form-horizontal">
                    @using (Html.BeginForm("InvoiceEntry", "Invoice", "Post"))
                    {
                        <div class="form-group">
                            <label class="control-label col-sm-4" for="ClientName">Client Name</label>
                            <div class="col-sm-8">
                                @Html.TextBoxFor(x => x.ClientName, new { @class = "form-control", @id = "ClientName" }) @Html.ValidationMessageFor(x => x.ClientName)
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-4" for="ClientAddress">Address</label>
                            <div class="col-sm-8">
                                @Html.TextBoxFor(x => x.ClientAddress, new { @class = "form-control", @id = "ClientAddress" }) @Html.ValidationMessageFor(x => x.ClientAddress)
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-4" for="ShipmentDate">Shipment Date</label>
                            <div class="col-sm-8">
                                @Html.EditorFor(x => x.ShipmentDate, new { htmlAttributes = new { @class = "form-control" } }) @Html.ValidationMessageFor(x => x.ShipmentDate)
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-4" for="PaymentDueDate">Payment Date</label>
                            <div class="col-sm-8">
                                @Html.EditorFor(x => x.PaymentDueDate, new { htmlAttributes = new { @class = "form-control" } }) @Html.ValidationMessageFor(x => x.PaymentDueDate)
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-4" for="ProductName">Product Name</label>
                            <div class="col-sm-8">
                                @Html.TextBoxFor(x => x.ProductName, new { @class = "form-control", @id = "ProductName" }) @Html.ValidationMessageFor(x => x.ProductName)
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-4" for="Quantity">Quantity</label>
                            <div class="col-sm-8">
                                @Html.TextBoxFor(x => x.Quantity, new { @class = "form-control", @id = "ProductName" }) @Html.ValidationMessageFor(x => x.Quantity)
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-4" for="UnitPrice">Unit Price</label>
                            <div class="col-sm-8">
                                @Html.TextBoxFor(x => x.UnitPrice, new { @class = "form-control", @id = "UnitPrice" }) @Html.ValidationMessageFor(x => x.UnitPrice)
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-4" for="Currency">Currency</label>
                            <div class="col-sm-8">
                                @Html.DropDownListFor(x => x.CurrencyType, new SelectList(Enum.GetNames(typeof(Currency))), new { @class = "form-control" })
                            </div>
                        </div>
                        if (ViewBag.isReviewing == true)
                        {
                            @Html.HiddenFor(x => x.InvoiceNumber)
                            <div class="form-group">
                                <label class="control-label col-sm-4" for="Subtotal">Subtotal:</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control"  disabled id="Subtotal" value="$@Model.InvoiceSubTotal()" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-4" for="Tax">Tax (10%)</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" disabled value="$@Model.InvoiceTax()" id="Tax" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-4" for="Total">Total</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" disabled value="$@Model.InvoiceTotal()" id="Total" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-4" for="Mark">Mark As Paid</label>
                                <div class="col-sm-8">
                                    <div id="Mark">@Html.CheckBoxFor(x => x.Paid)</div>
                                </div>
                            </div>
                        }
                        <div class="form-group">
                            <label class="control-label col-sm-4" for="submit"></label>
                            <div class="col-sm-8">
                                <input type="submit" class="btn btn-success" value="@ViewBag.submitBtn" id="submit" />
                            </div>
                        </div>
                        

                    }
                </div>
            </div>
            </div>
            <div class="col-sm-3"></div>
        </div>
}
else
{
    <div class="container">
        <div class="page-header text-center">
            <h1>Invoice Entry</h1>
        </div>
        </div>

    <h3 class="text-center" style="color: red;">ERROR 403: You are currently not authenticated. Please <a href="../UserAccount/Index">return</a> to the login screen</h3>
}
</body>
</html>

EnterpriseAppMvc/EnterpriseAppMvc/Views/Invoice/ViewInvoices.cshtml
@using EnterpriseAppMvc.Domain.Entities
@model IEnumerable<Invoice>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ViewInvoices</title>
    <link rel="stylesheet" type="text/css" href="~/Content/Style.css" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="page-header text-center">
            <h1>Outstanding Invoices</h1>
        </div>
    </div>
    <div>@{
        User user = (Session["UserAccount"]) as User;

        <h4 class="text-center" style="color: green;">@ViewBag.message</h4>
        if ((Session["UserAccount"]) != null)
        {
            if (user.Type >= UserType.Manager)
            {
                decimal total = 0;
        <table class="table table-striped">
            <thead>
                <tr><th>Invoice Number</th><th>Client Name</th><th>Payment Due Date</th><th>Invoice Total</th></tr>
            </thead>
            <tbody>
                @foreach (Invoice inv in Model)
                {
                    <tr>
                        @using (Html.BeginForm("ManageInvoice", "Invoice", "Post"))
                        {
                            <th><input type="submit" value="@inv.InvoiceNumber" /></th>
                            <td><input type="submit" value="@inv.ClientName" /></td>
                            @Html.Hidden("TrackingNum", inv.InvoiceNumber)

                        }
                        <td>@inv.PaymentDueDate.ToString("dd-MMMM-yyyy")</td>
                        <td>@inv.CurrencyType $@inv.InvoiceTotal()</td>
                    </tr>
                    total += inv.InvoiceTotal();

                }
            </tbody>
            <tfoot>
                <tr>
                    <td>@Html.ActionLink("Return Home", "Home", null, new { @class = "btn btn-primary" })</td>
                    <td>@Html.ActionLink("Add Invoice", "InvoiceEntry", null, new { @class = "btn btn-success" })</td>
                    <th>Total:</th>
                    <th>$@total</th>
                </tr>
            </tfoot>
        </table>
            }

        }
        else
        {

            <div class="text-center">
                <h3 class="text-center" style="color: red;">ERROR 403: You are currently not authenticated. Please <a href="../UserAccount/Index">return</a> to the login screen</h3>
            </div>
            }

        }</div>
</body>
</html>